version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: todo-root-password
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: todo-password
      MYSQL_DATABASE: todos
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
